server:
  port: 8082
logging:
  root:
    level: debug
spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///usersdb;DB_CLOSE_DELAY=-1
    username: sa
    password: